/**
 * @author Jordi Ros: shine.3p@gmail.com
 *
 */

// Boss1
EnemyActions.Boss1_1 = [
    { time: 0.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[0], -15, 80, 3); } },
    { time: 0.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10, 80, 3); } },
    { time: 0.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5, 80, 3); } },
    { time: 0.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 0, 80, 3); } },
    { time: 0.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5, 80, 3); } },
    { time: 1.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10, 80, 3); } },
    { time: 1.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -15, 80, 3); } },
    { time: 0.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[1], -15, 80, 3); } },
    { time: 0.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10, 80, 3); } },
    { time: 0.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5, 80, 3); } },
    { time: 0.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 0, 80, 3); } },
    { time: 0.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5, 80, 3); } },
    { time: 1.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10, 80, 3); } },
    { time: 1.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15, 80, 3); } },    
    
    { time: 3.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[0], -15, 80, 4); } },
    { time: 3.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10, 80, 4); } },
    { time: 3.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5, 80, 4); } },
    { time: 3.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 0, 80, 4); } },
    { time: 3.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5, 80, 4); } },
    { time: 4.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10, 80, 4); } },
    { time: 4.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -15, 80, 4); } },
    { time: 3.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[1], -15, 80, 4); } },
    { time: 3.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10, 80, 4); } },
    { time: 3.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5, 80, 4); } },
    { time: 3.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 0, 80, 4); } },
    { time: 3.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5, 80, 4); } },
    { time: 4.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10, 80, 4); } },
    { time: 4.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15, 80, 4); } },    
    
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },     
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },         
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },         
    { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },         
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 0, 1); } },        
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 0, 1); } },
    
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },     
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },         
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },         
    { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },         
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 0, 1); } },        
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 0, 1); } },         
];

EnemyActions.Boss1_2 = [
    { time: 2.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, true,  Enemies.Boss1.BOMini1[0], -4*5, 90, 5); } },
    { time: 2.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -4*5, 90, 5); } },
    { time: 2.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -3*5, 90, 5); } },
    { time: 2.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -3*5, 90, 5); } },
    { time: 2.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -2*5, 90, 5); } },
    { time: 2.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -2*5, 90, 5); } },
    { time: 2.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -1*5, 90, 5); } },
    { time: 2.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -1*5, 90, 5); } },
    { time: 2.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -0*5, 90, 5); } },
    { time: 2.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -0*5, 90, 5); } },    
    { time: 3.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  1*5, 90, 5); } },
    { time: 3.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  1*5, 90, 5); } },
    { time: 3.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  2*5, 90, 5); } },
    { time: 3.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  2*5, 90, 5); } },        
    { time: 3.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  3*5, 90, 5); } },
    { time: 3.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  3*5, 90, 5); } },
    
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 50, 2); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 50, 2); } },
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 50, 2); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 50, 2); } },     
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 50, 2); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 50, 2); } },
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 50, 2); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 50, 2); } },

    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 50, 2); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 50, 2); } },
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 50, 2); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 50, 2); } },         
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 50, 2); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 50, 2); } },
    { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 50, 2); } },
    { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 50, 2); } },     

    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 50, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 50, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 50, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 50, 1); } },         
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 50, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 50, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 50, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 50, 1); } },         
];

EnemyActions.Boss1_3 = [
    { time: 0.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[0], -15*1.2, 150, 5); } },
    { time: 0.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10*1.2, 150, 5); } },
    { time: 0.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5*1.2, 150, 5); } },
    { time: 0.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 0*1.2, 150, 5); } },
    { time: 0.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5*1.2, 150, 5); } },
    { time: 1.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10*1.2, 150, 5); } },
    { time: 1.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -15*1.2, 150, 5); } },
    { time: 0.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15*1.2, 150, 5); } },
    { time: 0.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10*1.2, 150, 5); } },
    { time: 0.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5*1.2, 150, 5); } },
    { time: 0.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 0*1.2, 150, 5); } },
    { time: 0.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5*1.2, 150, 5); } },
    { time: 1.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10*1.2, 150, 5); } },
    { time: 1.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15*1.2, 150, 5); } },    
    
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, true,  Enemies.Boss1.BOMini1[0], -3*5, 70, 4); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -3*5, 70, 4); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -2*5, 70, 4); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -2*5, 70, 4); } },
    { time: 2.90, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -1*5, 70, 4); } },
    { time: 2.90, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -1*5, 70, 4); } },
    { time: 3.10, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -0*5, 70, 4); } },
    { time: 3.10, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -0*5, 70, 4); } },
    { time: 3.30, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -1*5, 70, 4); } },
    { time: 3.30, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -1*5, 70, 4); } },    
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  2*5, 70, 4); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  2*5, 70, 4); } },        
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  3*5, 70, 4); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  3*5, 70, 4); } },            
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  3*5, 70, 4); } },
    
    { time: 4.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[0], -15*1.2, 150, 4); } },
    { time: 4.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10*1.2, 150, 4); } },
    { time: 4.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5*1.2, 150, 4); } },
    { time: 4.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 0*1.2, 150, 4); } },
    { time: 4.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5*1.2, 150, 4); } },
    { time: 5.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10*1.2, 150, 4); } },
    { time: 5.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -15*1.2, 150, 4); } },
    { time: 4.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15*1.2, 150, 4); } },
    { time: 4.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10*1.2, 150, 4); } },
    { time: 4.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5*1.2, 150, 4); } },
    { time: 4.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 0*1.2, 150, 4); } },
    { time: 4.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5*1.2, 150, 4); } },
    { time: 5.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10*1.2, 150, 4); } },
    { time: 5.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15*1.2, 150, 4); } },    

];

EnemyActions.Boss1_4 = [
    { time: 1.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, true,  Enemies.Boss1.BOMini1[0], -3*1, 120, 5); } },
    { time: 1.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -3*1, 120, 5); } },
    { time: 1.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -2*1, 120, 5); } },
    { time: 1.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -2*1, 120, 5); } },
    { time: 1.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -1*1, 120, 5); } },
    { time: 1.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -1*1, 120, 5); } },
    { time: 1.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -0*1, 120, 5); } },
    { time: 1.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -0*1, 120, 5); } },
    { time: 1.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0], -1*1, 120, 5); } },
    { time: 1.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1], -1*1, 120, 5); } },    
    { time: 2.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  2*1, 120, 5); } },
    { time: 2.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  2*1, 120, 5); } },
    { time: 2.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[0],  3*1, 120, 5); } },
    { time: 2.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.PlasmaPinkBig, entity, time, false, Enemies.Boss1.BOMini1[1],  3*1, 120, 5); } },        
    
    { time: 4.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, true,  Enemies.Boss1.BOBig[0], -15*1.2, 150, 5); } },
    { time: 4.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10*1.2, 150, 5); } },
    { time: 4.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5*1.2, 150, 5); } },
    { time: 4.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 0*1.2, 150, 5); } },
    { time: 4.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], - 5*1.2, 150, 5); } },
    { time: 5.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -10*1.2, 150, 5); } },
    { time: 5.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[0], -15*1.2, 150, 5); } },
    { time: 4.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15*1.2, 150, 5); } },
    { time: 4.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10*1.2, 150, 5); } },
    { time: 4.40, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5*1.2, 150, 5); } },
    { time: 4.60, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 0*1.2, 150, 5); } },
    { time: 4.80, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], - 5*1.2, 150, 5); } },
    { time: 5.00, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -10*1.2, 150, 5); } },
    { time: 5.20, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Plasma, entity, time, false, Enemies.Boss1.BOBig[1], -15*1.2, 150, 5); } },    
    
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },     
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 0.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },
    { time: 0.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },     
    
    // { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 30, 2); } },
    // { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 30, 2); } },
    // { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 2); } },
    // { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 2); } },
    // { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 3); } },
    // { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 3); } },
    // { time: 1.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 3); } },
    // { time: 1.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 3); } },     
    
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 2.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },
    { time: 2.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },
    
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },         
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 3.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },
    { time: 3.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },         
    
    // { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 30, 2); } },
    // { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 30, 2); } },
    // { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 2); } },
    // { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 2); } },         
    // { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 3); } },
    // { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 3); } },
    // { time: 4.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 3); } },
    // { time: 4.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 3); } },         
    
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, true,  Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[0], 0, 30, 1); } },        
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[0], 0, 30, 1); } },
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser1[1], 0, 30, 1); } },        
    { time: 5.50, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },
    { time: 5.70, action: function(entity, time) { Bullets.ShootTargetCircle(Bullets.Boss1Laser, entity, time, false, Enemies.Boss1.BOLaser2[1], 0, 30, 1); } },             
];
